// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/recycling.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecyclingItem_BinColour int32

const (
	RecyclingItem_BIN_COLOUR_UNKNOWN RecyclingItem_BinColour = 0
	RecyclingItem_BLUE               RecyclingItem_BinColour = 1
	RecyclingItem_GREEN              RecyclingItem_BinColour = 2
	RecyclingItem_BROWN              RecyclingItem_BinColour = 3
	RecyclingItem_BLACK              RecyclingItem_BinColour = 4
)

// Enum value maps for RecyclingItem_BinColour.
var (
	RecyclingItem_BinColour_name = map[int32]string{
		0: "BIN_COLOUR_UNKNOWN",
		1: "BLUE",
		2: "GREEN",
		3: "BROWN",
		4: "BLACK",
	}
	RecyclingItem_BinColour_value = map[string]int32{
		"BIN_COLOUR_UNKNOWN": 0,
		"BLUE":               1,
		"GREEN":              2,
		"BROWN":              3,
		"BLACK":              4,
	}
)

func (x RecyclingItem_BinColour) Enum() *RecyclingItem_BinColour {
	p := new(RecyclingItem_BinColour)
	*p = x
	return p
}

func (x RecyclingItem_BinColour) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecyclingItem_BinColour) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recycling_proto_enumTypes[0].Descriptor()
}

func (RecyclingItem_BinColour) Type() protoreflect.EnumType {
	return &file_proto_recycling_proto_enumTypes[0]
}

func (x RecyclingItem_BinColour) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecyclingItem_BinColour.Descriptor instead.
func (RecyclingItem_BinColour) EnumDescriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{0, 0}
}

type RecyclingItem_BinType int32

const (
	RecyclingItem_BIN_TYPE_UNKNOWN RecyclingItem_BinType = 0
	RecyclingItem_PAPER            RecyclingItem_BinType = 1
	RecyclingItem_RECYCLING        RecyclingItem_BinType = 2
	RecyclingItem_GLASS            RecyclingItem_BinType = 3
	RecyclingItem_WASTE            RecyclingItem_BinType = 4
)

// Enum value maps for RecyclingItem_BinType.
var (
	RecyclingItem_BinType_name = map[int32]string{
		0: "BIN_TYPE_UNKNOWN",
		1: "PAPER",
		2: "RECYCLING",
		3: "GLASS",
		4: "WASTE",
	}
	RecyclingItem_BinType_value = map[string]int32{
		"BIN_TYPE_UNKNOWN": 0,
		"PAPER":            1,
		"RECYCLING":        2,
		"GLASS":            3,
		"WASTE":            4,
	}
)

func (x RecyclingItem_BinType) Enum() *RecyclingItem_BinType {
	p := new(RecyclingItem_BinType)
	*p = x
	return p
}

func (x RecyclingItem_BinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecyclingItem_BinType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recycling_proto_enumTypes[1].Descriptor()
}

func (RecyclingItem_BinType) Type() protoreflect.EnumType {
	return &file_proto_recycling_proto_enumTypes[1]
}

func (x RecyclingItem_BinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecyclingItem_BinType.Descriptor instead.
func (RecyclingItem_BinType) EnumDescriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{0, 1}
}

// Messages for recycling items
type RecyclingItem struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Recyclable    bool                    `protobuf:"varint,1,opt,name=recyclable,proto3" json:"recyclable,omitempty"`
	Advice        string                  `protobuf:"bytes,2,opt,name=advice,proto3" json:"advice,omitempty"`
	BinColour     RecyclingItem_BinColour `protobuf:"varint,3,opt,name=bin_colour,json=binColour,proto3,enum=recycling.RecyclingItem_BinColour" json:"bin_colour,omitempty"`
	BinType       RecyclingItem_BinType   `protobuf:"varint,4,opt,name=bin_type,json=binType,proto3,enum=recycling.RecyclingItem_BinType" json:"bin_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecyclingItem) Reset() {
	*x = RecyclingItem{}
	mi := &file_proto_recycling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecyclingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecyclingItem) ProtoMessage() {}

func (x *RecyclingItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recycling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecyclingItem.ProtoReflect.Descriptor instead.
func (*RecyclingItem) Descriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{0}
}

func (x *RecyclingItem) GetRecyclable() bool {
	if x != nil {
		return x.Recyclable
	}
	return false
}

func (x *RecyclingItem) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

func (x *RecyclingItem) GetBinColour() RecyclingItem_BinColour {
	if x != nil {
		return x.BinColour
	}
	return RecyclingItem_BIN_COLOUR_UNKNOWN
}

func (x *RecyclingItem) GetBinType() RecyclingItem_BinType {
	if x != nil {
		return x.BinType
	}
	return RecyclingItem_BIN_TYPE_UNKNOWN
}

type CanItBeRecycledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanItBeRecycledRequest) Reset() {
	*x = CanItBeRecycledRequest{}
	mi := &file_proto_recycling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanItBeRecycledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanItBeRecycledRequest) ProtoMessage() {}

func (x *CanItBeRecycledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recycling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanItBeRecycledRequest.ProtoReflect.Descriptor instead.
func (*CanItBeRecycledRequest) Descriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{1}
}

func (x *CanItBeRecycledRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type CanItBeRecycledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *RecyclingItem         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanItBeRecycledResponse) Reset() {
	*x = CanItBeRecycledResponse{}
	mi := &file_proto_recycling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanItBeRecycledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanItBeRecycledResponse) ProtoMessage() {}

func (x *CanItBeRecycledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recycling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanItBeRecycledResponse.ProtoReflect.Descriptor instead.
func (*CanItBeRecycledResponse) Descriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{2}
}

func (x *CanItBeRecycledResponse) GetData() *RecyclingItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CanItBeRecycledImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanItBeRecycledImageRequest) Reset() {
	*x = CanItBeRecycledImageRequest{}
	mi := &file_proto_recycling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanItBeRecycledImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanItBeRecycledImageRequest) ProtoMessage() {}

func (x *CanItBeRecycledImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recycling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanItBeRecycledImageRequest.ProtoReflect.Descriptor instead.
func (*CanItBeRecycledImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{3}
}

func (x *CanItBeRecycledImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type CanItBeRecycledImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *RecyclingItem         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanItBeRecycledImageResponse) Reset() {
	*x = CanItBeRecycledImageResponse{}
	mi := &file_proto_recycling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanItBeRecycledImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanItBeRecycledImageResponse) ProtoMessage() {}

func (x *CanItBeRecycledImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recycling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanItBeRecycledImageResponse.ProtoReflect.Descriptor instead.
func (*CanItBeRecycledImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_recycling_proto_rawDescGZIP(), []int{4}
}

func (x *CanItBeRecycledImageResponse) GetData() *RecyclingItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_recycling_proto protoreflect.FileDescriptor

const file_proto_recycling_proto_rawDesc = "" +
	"\n" +
	"\x15proto/recycling.proto\x12\trecycling\"\xe8\x02\n" +
	"\rRecyclingItem\x12\x1e\n" +
	"\n" +
	"recyclable\x18\x01 \x01(\bR\n" +
	"recyclable\x12\x16\n" +
	"\x06advice\x18\x02 \x01(\tR\x06advice\x12A\n" +
	"\n" +
	"bin_colour\x18\x03 \x01(\x0e2\".recycling.RecyclingItem.BinColourR\tbinColour\x12;\n" +
	"\bbin_type\x18\x04 \x01(\x0e2 .recycling.RecyclingItem.BinTypeR\abinType\"N\n" +
	"\tBinColour\x12\x16\n" +
	"\x12BIN_COLOUR_UNKNOWN\x10\x00\x12\b\n" +
	"\x04BLUE\x10\x01\x12\t\n" +
	"\x05GREEN\x10\x02\x12\t\n" +
	"\x05BROWN\x10\x03\x12\t\n" +
	"\x05BLACK\x10\x04\"O\n" +
	"\aBinType\x12\x14\n" +
	"\x10BIN_TYPE_UNKNOWN\x10\x00\x12\t\n" +
	"\x05PAPER\x10\x01\x12\r\n" +
	"\tRECYCLING\x10\x02\x12\t\n" +
	"\x05GLASS\x10\x03\x12\t\n" +
	"\x05WASTE\x10\x04\"2\n" +
	"\x16CanItBeRecycledRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"G\n" +
	"\x17CanItBeRecycledResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.recycling.RecyclingItemR\x04data\"3\n" +
	"\x1bCanItBeRecycledImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"L\n" +
	"\x1cCanItBeRecycledImageResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.recycling.RecyclingItemR\x04data2\xd5\x01\n" +
	"\x10RecyclingService\x12X\n" +
	"\x0fCanItBeRecycled\x12!.recycling.CanItBeRecycledRequest\x1a\".recycling.CanItBeRecycledResponse\x12g\n" +
	"\x14CanItBeRecycledImage\x12&.recycling.CanItBeRecycledImageRequest\x1a'.recycling.CanItBeRecycledImageResponseB\x19Z\x17recycling-service/protob\x06proto3"

var (
	file_proto_recycling_proto_rawDescOnce sync.Once
	file_proto_recycling_proto_rawDescData []byte
)

func file_proto_recycling_proto_rawDescGZIP() []byte {
	file_proto_recycling_proto_rawDescOnce.Do(func() {
		file_proto_recycling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recycling_proto_rawDesc), len(file_proto_recycling_proto_rawDesc)))
	})
	return file_proto_recycling_proto_rawDescData
}

var file_proto_recycling_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_recycling_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_recycling_proto_goTypes = []any{
	(RecyclingItem_BinColour)(0),         // 0: recycling.RecyclingItem.BinColour
	(RecyclingItem_BinType)(0),           // 1: recycling.RecyclingItem.BinType
	(*RecyclingItem)(nil),                // 2: recycling.RecyclingItem
	(*CanItBeRecycledRequest)(nil),       // 3: recycling.CanItBeRecycledRequest
	(*CanItBeRecycledResponse)(nil),      // 4: recycling.CanItBeRecycledResponse
	(*CanItBeRecycledImageRequest)(nil),  // 5: recycling.CanItBeRecycledImageRequest
	(*CanItBeRecycledImageResponse)(nil), // 6: recycling.CanItBeRecycledImageResponse
}
var file_proto_recycling_proto_depIdxs = []int32{
	0, // 0: recycling.RecyclingItem.bin_colour:type_name -> recycling.RecyclingItem.BinColour
	1, // 1: recycling.RecyclingItem.bin_type:type_name -> recycling.RecyclingItem.BinType
	2, // 2: recycling.CanItBeRecycledResponse.data:type_name -> recycling.RecyclingItem
	2, // 3: recycling.CanItBeRecycledImageResponse.data:type_name -> recycling.RecyclingItem
	3, // 4: recycling.RecyclingService.CanItBeRecycled:input_type -> recycling.CanItBeRecycledRequest
	5, // 5: recycling.RecyclingService.CanItBeRecycledImage:input_type -> recycling.CanItBeRecycledImageRequest
	4, // 6: recycling.RecyclingService.CanItBeRecycled:output_type -> recycling.CanItBeRecycledResponse
	6, // 7: recycling.RecyclingService.CanItBeRecycledImage:output_type -> recycling.CanItBeRecycledImageResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_recycling_proto_init() }
func file_proto_recycling_proto_init() {
	if File_proto_recycling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recycling_proto_rawDesc), len(file_proto_recycling_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recycling_proto_goTypes,
		DependencyIndexes: file_proto_recycling_proto_depIdxs,
		EnumInfos:         file_proto_recycling_proto_enumTypes,
		MessageInfos:      file_proto_recycling_proto_msgTypes,
	}.Build()
	File_proto_recycling_proto = out.File
	file_proto_recycling_proto_goTypes = nil
	file_proto_recycling_proto_depIdxs = nil
}
