// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/recycling.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecyclingService_CanItBeRecycled_FullMethodName       = "/recycling.RecyclingService/CanItBeRecycled"
	RecyclingService_CanItBeRecycledSearch_FullMethodName = "/recycling.RecyclingService/CanItBeRecycledSearch"
	RecyclingService_CanItBeRecycledImage_FullMethodName  = "/recycling.RecyclingService/CanItBeRecycledImage"
)

// RecyclingServiceClient is the client API for RecyclingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type RecyclingServiceClient interface {
	CanItBeRecycled(ctx context.Context, in *CanItBeRecycledRequest, opts ...grpc.CallOption) (*CanItBeRecycledResponse, error)
	CanItBeRecycledSearch(ctx context.Context, in *CanItBeRecycledSearchRequest, opts ...grpc.CallOption) (*CanItBeRecycledSearchResponse, error)
	CanItBeRecycledImage(ctx context.Context, in *CanItBeRecycledImageRequest, opts ...grpc.CallOption) (*CanItBeRecycledImageResponse, error)
}

type recyclingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecyclingServiceClient(cc grpc.ClientConnInterface) RecyclingServiceClient {
	return &recyclingServiceClient{cc}
}

func (c *recyclingServiceClient) CanItBeRecycled(ctx context.Context, in *CanItBeRecycledRequest, opts ...grpc.CallOption) (*CanItBeRecycledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanItBeRecycledResponse)
	err := c.cc.Invoke(ctx, RecyclingService_CanItBeRecycled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recyclingServiceClient) CanItBeRecycledSearch(ctx context.Context, in *CanItBeRecycledSearchRequest, opts ...grpc.CallOption) (*CanItBeRecycledSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanItBeRecycledSearchResponse)
	err := c.cc.Invoke(ctx, RecyclingService_CanItBeRecycledSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recyclingServiceClient) CanItBeRecycledImage(ctx context.Context, in *CanItBeRecycledImageRequest, opts ...grpc.CallOption) (*CanItBeRecycledImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanItBeRecycledImageResponse)
	err := c.cc.Invoke(ctx, RecyclingService_CanItBeRecycledImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecyclingServiceServer is the server API for RecyclingService service.
// All implementations must embed UnimplementedRecyclingServiceServer
// for forward compatibility.
//
// Service definition
type RecyclingServiceServer interface {
	CanItBeRecycled(context.Context, *CanItBeRecycledRequest) (*CanItBeRecycledResponse, error)
	CanItBeRecycledSearch(context.Context, *CanItBeRecycledSearchRequest) (*CanItBeRecycledSearchResponse, error)
	CanItBeRecycledImage(context.Context, *CanItBeRecycledImageRequest) (*CanItBeRecycledImageResponse, error)
	mustEmbedUnimplementedRecyclingServiceServer()
}

// UnimplementedRecyclingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecyclingServiceServer struct{}

func (UnimplementedRecyclingServiceServer) CanItBeRecycled(context.Context, *CanItBeRecycledRequest) (*CanItBeRecycledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanItBeRecycled not implemented")
}
func (UnimplementedRecyclingServiceServer) CanItBeRecycledSearch(context.Context, *CanItBeRecycledSearchRequest) (*CanItBeRecycledSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanItBeRecycledSearch not implemented")
}
func (UnimplementedRecyclingServiceServer) CanItBeRecycledImage(context.Context, *CanItBeRecycledImageRequest) (*CanItBeRecycledImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanItBeRecycledImage not implemented")
}
func (UnimplementedRecyclingServiceServer) mustEmbedUnimplementedRecyclingServiceServer() {}
func (UnimplementedRecyclingServiceServer) testEmbeddedByValue()                          {}

// UnsafeRecyclingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecyclingServiceServer will
// result in compilation errors.
type UnsafeRecyclingServiceServer interface {
	mustEmbedUnimplementedRecyclingServiceServer()
}

func RegisterRecyclingServiceServer(s grpc.ServiceRegistrar, srv RecyclingServiceServer) {
	// If the following call panics, it indicates UnimplementedRecyclingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecyclingService_ServiceDesc, srv)
}

func _RecyclingService_CanItBeRecycled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanItBeRecycledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecyclingServiceServer).CanItBeRecycled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecyclingService_CanItBeRecycled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecyclingServiceServer).CanItBeRecycled(ctx, req.(*CanItBeRecycledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecyclingService_CanItBeRecycledSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanItBeRecycledSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecyclingServiceServer).CanItBeRecycledSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecyclingService_CanItBeRecycledSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecyclingServiceServer).CanItBeRecycledSearch(ctx, req.(*CanItBeRecycledSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecyclingService_CanItBeRecycledImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanItBeRecycledImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecyclingServiceServer).CanItBeRecycledImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecyclingService_CanItBeRecycledImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecyclingServiceServer).CanItBeRecycledImage(ctx, req.(*CanItBeRecycledImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecyclingService_ServiceDesc is the grpc.ServiceDesc for RecyclingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecyclingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recycling.RecyclingService",
	HandlerType: (*RecyclingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanItBeRecycled",
			Handler:    _RecyclingService_CanItBeRecycled_Handler,
		},
		{
			MethodName: "CanItBeRecycledSearch",
			Handler:    _RecyclingService_CanItBeRecycledSearch_Handler,
		},
		{
			MethodName: "CanItBeRecycledImage",
			Handler:    _RecyclingService_CanItBeRecycledImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/recycling.proto",
}
